# Generated by Django 5.1.4 on 2025-01-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estt_main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team_user',
        ),
    ]
