# Generated by Django 5.1.4 on 2025-01-05 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estt_main_app', '0005_target_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estt_main_app.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estt_main_app.team')),
            ],
        ),
    ]
