# Generated by Django 5.1.4 on 2025-04-19 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estt_main_app', '0012_org_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 19, 2, 10, 32, 444509, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
